CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'ale-roux'@'%' IDENTIFIED BY '42';
GRANT ALL PRIVILEGES ON wordpress.* TO 'ale-roux'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';
