FROM debian:bookworm

RUN apt update && apt install -y nginx openssl
RUN apt clean --dry-run

EXPOSE 443

COPY ./conf/default/ /etc/nginx/sites-enabled/default
COPY ./tools/nginx_start.sh /var/www

RUN chmod +x /var/www/nginx_start.sh

ENTRYPOINT ["var/www/nginx_start.sh"]

CMD ["nginx", "-g", "daemon off;"]

